---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    download_path: "{{ lookup('env','HOME') }}/Downloads"
  vars_prompt:
    - name: username
      prompt: "What is your username?"
      private: no

  tasks:
    - name: Check to Ensure Python Dependencies are Installed
      package: name={{ item }} state=present
      with_items:
        - python2
        - python2-dnf
        - python-pip
        - libselinux-python

    - name: Install VirtualBox Dependencies
      package: name={{ item }} state=present
      with_items:
        - binutils
        - gcc
        - make
        - patch
        - libgomp
        - glibc-headers
        - glibc-devel
        - kernel-headers
        - kernel-devel
        - dkms

    - name: Add VirtualBox Repository Public Key
      rpm_key: state=present key=https://www.virtualbox.org/download/oracle_vbox.asc

    - name: Add VirtualBox Repository
      yum_repository:
        file: virtualbox
        name: virtualbox
        description: VirtualBox Repository
        baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc

    - name: Install VirtualBox 5.0
      dnf: name=VirtualBox-5.0 state=latest

    - name: Get Current Linux Kernel Version
      command: uname -r
      register: uname_output

    - debug: var=uname_output

    - name: Set Environment Variable KERN_DIR
      blockinfile:
        dest: ~/.bashrc
        content: |
          export KERN_DIR=/usr/src/kernels/{{ uname_output.stdout }}
      become: true
      become_user: "{{ username }}"

    - name: Load vboxdrv Kernel Module
      command: /usr/lib/virtualbox/vboxdrv.sh setup

    - name: Fix Oracle's Problem with SELinux so VirtualBox Will Run
      command: /usr/lib/virtualbox/vboxdrv.sh setup

    - name: Install Vagrant and Dependencies
      package: name={{ item }} state=present
      with_items:
        - vagrant
        - ruby-devel
        - redhat-rpm-config
        - zlib-devel

    - name: Install Vagrant Cachier Plugin
      command: vagrant plugin install vagrant-cachier
    - name: Install Vagrant Hostmanager Plugin
      command: vagrant plugin install vagrant-hostmanager

    - name: Set VirtualBox as Default Provider for Vagrant
      blockinfile: 
        dest: ~/.bashrc
        content: |
          export VAGRANT_DEFAULT_PROVIDER=virtualbox
      become: true
      become_user: "{{ username }}"

    - name: Source .bashrc
      shell: source /home/"{{ username}}"/.bashrc

    - name: Install RPMFusion Repository
      dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm state=present
    
    - name: Install Optional Utilities
      package: name={{ item }} state=present
      with_items:
        - tmux
        - vim-enhanced
        - vlc
        - gnome-tweak-tool
        - guake

    - name: Install Google Chrome Repository
      command: >
        cp ./files/google-chrome.repo /etc/yum.repos.d/

    - name: Install Google Chrome Browser
      package: name=google-chrome-stable state=present

    - name: Install Hipchat Repository
      command: >
        cp ./files/hipchat.repo /etc/yum.repos.d/

    - name: Install Hipchat
      package: name=hipchat4 state=present
