---
- hosts: all
  become: true
  become_method: sudo
  become_user: root
  vars:
    download_path: "{{ lookup('env','HOME') }}/Downloads"
  
  tasks:
    - name: Install Python2 so DNF works with Vagrant
      package: name={{ item }} state=present 
      with_items:
        - python2 
        - python2-dnf
        - python-pip

    - name: Install VirtualBox Dependencies
      package: name={{ item }} state=present
      with_items:
        - binutils
        - gcc
        - make
        - patch
        - libgomp
        - glibc-headers
        - glibc-devel
        - kernel-headers
        - kernel-devel
        - dkms
    - name: Add VirtualBox Repo Public Key
      rpm_key: state=present key=https://www.virtualbox.org/download/oracle_vbox.asc

    - name: Add VirtualBox Repo
      yum_repository:
        file: virtualbox
        name: virtualbox
        description: VirtualBox Repository
        baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
    
    - name: Install VirtualBox 5.0
      dnf: name=VirtualBox-5.0 state=latest

    - name: Get the current linux version
      command: uname -r
      register: uname_output

    - debug: var=uname_output
 
    - name: Set the environment varible KERN_DIR
      blockinfile:
        dest: ~/.bashrc
        content: |
          export KERN_DIR=/usr/src/kernels/{{ uname_output.stdout }}
      become: true
      become_user: vagrant

    - name: Load vboxdrv kernel module
      command: /sbin/rcvboxdrv setup

    - name: Install Vagrant and Dependencies
      package: name={{ item }} state=present
      with_items:
        - vagrant
        - ruby-devel
        - redhat-rpm-config
        - zlib-devel

    - name: Install Vagrant Cachier
      command: vagrant plugin install vagrant-cachier
    - name: Install Vagrant Hostmanager
      command: vagrant plugin install vagrant-hostmanager

    - name: Install Ansible
      package: name=ansible state=present

    - name: Install Git
      package: name=git state=present

 
    - name: Install RPMFusion repository
      yum_repository:
        name: RPMFusion
        description: RPMFusion Repo
        file: external_repos
        baseurl: http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-stable.noarch.rpm
    - name: Install Utilities
      dnf: name={{ item }} state=latest
      with_items:
        - vlc
        - vim-enhanced

    - name: Clone Liquid Prompt using Git
      become: true
      become_user: vagrant
      git:
        repo: https://github.com/nojhan/liquidprompt
        dest: ~/liquidprompt
        
    - name: Enable Liquid Prompt
      become: true
      become_user: vagrant
      command: source liquidprompt/liquidprompt
